name: "Setup Bun"
description: "Setup to run task in scripts"
runs:
  using: "composite"
  steps:
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - uses: actions/cache@v3
      # - uses: useblacksmith/cache@v5
      name: Setup bun cache
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-store-v4-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-bun-store-v4

    - name: Set TODAY env variable
      run: echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      shell: bash

    - name: Install dependencies
      run: bun install --frozen-lockfile
      shell: bash
      working-directory: scripts
