on:
  schedule:
    - cron: 0 8 * * *
  workflow_dispatch:

name: Run Codegen
jobs:
  table-metadata:
    name: Run Codegen
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install
        working-directory: scripts/table-metadata

      - name: Run Codegen
        run: bun run codegen
        working-directory: scripts/table-metadata

      - name: Status
        run: git status

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        id: cpr
        with:
          commit-message: "chore: codegen"
          title: "chore: codegen"
          body: "Ran codegen and updated derived types"
          branch: "${{ steps.date.outputs.date }}-chore-codegen-table-metadata"
          base: main

      - name: Enable Pull Request Automerge
        run: gh pr merge --squash --auto "${{ steps.cpr.outputs.pull-request-number }}"
