on:
  schedule:
    - cron: 0 8 * * *
  workflow_dispatch:

name: Run Update Metadata Scripts
jobs:
  update-metadata:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup bun
        uses: ./.github/actions/setup

      - name: Store GCO Credentials
        env:
          GCP_SERVICE_ACCOUNT_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
        shell: bash
        run: echo "$GCP_SERVICE_ACCOUNT_JSON" > ${{ runner.temp }}/gateway_service_account.json

      - name: Run Tables Metadata
        run: bun run table-metadata
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{runner.temp}}/gateway_service_account.json
        working-directory: scripts

      - name: Status
        run: git status

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        id: cpr
        with:
          commit-message: "chore: update table metadata"
          title: "chore: update table metadata"
          body: "updated table definitions from BigQuery"
          branch: "${{ steps.date.outputs.date }}-chore-codegen-update-metadata"
          base: main

      - name: Enable Pull Request Automerge
        run: gh pr merge --squash --auto "${{ steps.cpr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
