on:
  schedule:
    - cron: 0 8 * * *
  workflow_dispatch:

name: Run Update Metadata Scripts
jobs:
  update-metadata:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install
        working-directory: scripts

      - name: Run Tables Metadata
        run: bun run table-metadata
        working-directory: scripts

      - name: Status
        run: git status

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        id: cpr
        with:
          commit-message: "chore: update metadata"
          title: "chore: update metadata"
          body: "Ran update metadata and updated table definitions"
          branch: "${{ steps.date.outputs.date }}-chore-codegen-update-metadata"
          base: main

      - name: Enable Pull Request Automerge
        run: gh pr merge --squash --auto "${{ steps.cpr.outputs.pull-request-number }}"
